---
- hosts: all
  vars:
    mqtt_port: 1883
  remote_user: ec2-user
  become: true
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  tasks:
    - copy: src=epel.repo dest=/etc/yum.repos.d/epel.repo owner=root group=root mode=0644
    - yum: name='*' state=latest exclude='kernel*'
    - get_url: 
        url: 'http://download.opensuse.org/repositories/home:/oojah:/mqtt/CentOS_CentOS-7/home:oojah:mqtt.repo'
        dest: /etc/yum.repos.d/mqtt.repo
    - yum: state=present name={{ item }}
      with_items:
        - mosquitto
        - mosquitto-clients
    - service: name=mosquitto enabled=no state=stopped
    - pip: name=pip extra_args='--upgrade'
    - pip: name=supervisor
    - pip: name=paho-mqtt
    - copy: src=supervisor-init dest=/etc/init.d/supervisor mode=0755
    - copy: src=supervisor-sysconfig dest=/etc/sysconfig/supervisor mode=0644
    - copy: src=supervisord.conf dest=/etc/supervisord.conf mode=0644
    - file: path=/etc/supervisor.d/ state=directory mode=0755
    - file: path=/var/log/supervisor state=directory mode=0755
    - copy: src=ncpws.conf dest=/etc/supervisor.d/ncpws.conf mode=0644
    - copy: src=../NCPWS_server_data_logger.py dest=/home/ec2-user/NCPWS_server_data_logger.py mode=0644
    - copy: src=config.json dest=/home/ec2-user/config.json mode=0644
    - command: chkconfig --add supervisor
    - service: name=supervisor enabled=yes state=stopped
    - service: name=supervisor enabled=yes state=started
    - authorized_key:
        user: ec2-user
        state: present
        key: "{{ item }}"
      with_items:
        - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8mUBqS/t4yc+iXFnQKreUlKNG/yXDMQbWDmS8Phq/BGUIEGF0/tdbPoV/wsaMqPg89iiHOoN2K/ZLki2cobiGqH+gWWx8Fy17IezZCe6Bq8qlrB/tdbRgNCwqhef0dmuiAbX78sJleHE9tn9/2nUz0XFbe/hhTends3+uheVqxtPnFbZQe9E4Ji6H6h/doiOXq+q/yXSDTxLZ+MfEmvMSiZTxHvlsW9CtdZYOyK4+EzFcExy5EW1drsciT5Imw2Dzm2A8ow0MzzJVIENa9Vx/zlERSINFiCzlBOXgEwdmsVWTeUAXfkbirLVwFJsnCY3mMTw2iyfGPAwxy4VBWTUx vakkermans@Brutus"
        - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCeJqFqZu/Wzo34KhmOKpusNgFpMf4vo/GHne6LsGw9APrK/IMNrvYbbXQsCDAx0OYE0urObcUDLdxETQseWSt5M5yX5s32uNjcma6qFLZcM4/zKYldfweedPAW/dKSSF3bk8b8oba09kKT5oB+SB4hvoeC9UgsyEoGzXJN5M7fP+QtRU/hkTBY+FnjQ/6AklWnmuWS2jvZOnH4RBY9eCtZLzqdpPlOU4/rjNPdM9Ilr4SuViCkCX0lIZBsaK9BP3dWKywwhkgvhOqPJ59fPn3zdct37j7jZBWivRhGESXWlhmQF5qH9IgaxAktXLE9tR4X46xaVbc1qqRXt/CMfi4F user@users-MBP.lan"
      tags: ssh

